---
title: "Untitled"
author: "Even Grindstad Brovold"
date: "15 oktober 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
library(mosaic)
library(ggplot2)
```



```{r}
getwd()



births <- read_fwf("Nat2017PublicUS.c20180516.r20180808.txt", 
                       fwf_positions(start = c(13,475,504),
                       end = c(14,475,507),
                       col_names = c("birth_month","gender", "birth_weight")))

```

```{r}
births$birth_month <- as.numeric(births$birth_month)
births$gender <- as.factor(births$gender)
births$birth_weight <- as.numeric(births$birth_weight)


births <- births %>% filter(birth_weight < 9999) 

favstats(~birth_month, data = births)


```

##Antall fødsler per kjønn.

```{r}

tally(~gender, data = births)
tally(~gender, data = births, format = "percent")

```

```{r}
favstats(~birth_weight, data = births)
```
##Grafisk fremstilling av vekt ved fødsel. Her ser vi tydelig en standard normalfordeling.
```{r}
ggplot(data = births, aes(x = birth_weight)) + geom_histogram(binwidth = 50) + 
  labs(title = "Histogram av vekt ved fødsel") 
```

```{r}
ggplot(data = births, aes(x = birth_weight)) + geom_density() + 
  labs(title = "Density Plot of Birth Weight in grams") 
```

#Oversikt på nøkkeltall per kjønn.
```{r}
favstats(~birth_weight|gender, data = births)

```

#Plotter begge kjønn og finner at illusterer grafisk at gutter er tyngre ved fødsel.
```{r}


ggplot() + geom_density(data=births, aes(x=birth_weight, group=gender, fill=gender), alpha=0.5, adjust=2) + 
  xlab("Birth Weight in grams") + ylab("Density")

```

#Formel test av forskjellig fødselsvekt.
```{r}
summary(lm(birth_weight~gender, data = births))

```

#Forskjell i gjennomsnittsvekten mellom gutter og jenter.
```{r}

diffmean(birth_weight~gender, data = births)
```



